//
// Created by Patrick on 2019-11-12.
//

#ifndef GENETICALGORITHM_CONSTANTS_HPP
#define GENETICALGORITHM_CONSTANTS_HPP

#define CITIES_IN_TOUR 32
#define POPULATION_SIZE 32
#define SHUFFLES 64
#define ITERATIONS 1000
#define MAP_BOUNDARY 1000
#define PARENT_POOL_SIZE 5
#define MUTATION_RATE 0.15 //15%


#endif //GENETICALGORITHM_CONSTANTS_HPP
